embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/core.js

stylesheets:
  main:
    - public/stylesheets/reset.css
    - public/stylesheets/grids.css
    #- public/stylesheets/formtastic.css
    #- public/stylesheets/formtastic_changes.css
    - public/stylesheets/flutie_mod.css
    - public/stylesheets/main.css
  admin:
    - public/stylesheets/reset.css
    - public/stylesheets/grids.css
    #- public/stylesheets/formtastic.css
    #- public/stylesheets/formtastic_changes.css
    - public/stylesheets/flutie_mod.css
    - public/stylesheets/main.css
    - public/stylesheets/admin.css